services:
  db:
    image: postgis/postgis:17-3.6-alpine
    platform: linux/amd64
    container_name: smarthome_db
    env_file:
      - .env
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - smarthome-network-dev

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: smarthome-backend-dev
    ports:
      - "${BACKEND_PORT}:5500"
    volumes:
      - backend-data:/app/data
    networks:
      - smarthome-network
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: smarthome-frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    networks:
      - smarthome-network-dev
    depends_on:
      - backend

  scene-creator:
    build:
      context: ./apps/scene-creator
      dockerfile: Dockerfile
    container_name: smarthome-scene-creator
    env_file:
      - .env
    ports:
      - "${SCENE_CREATOR_PORT}:8081"
    networks:
      - smarthome-network-dev
    depends_on:
      - backend

volumes:
  backend-data:
    name: smarthome-backend-data
  db_data:
    name: smarthome-db-data

networks:
  smarthome-network-dev:
    driver: bridge
    name: smarthome-network-dev
