# Generated by Django 5.2.7 on 2026-01-04 18:51

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=255)),
                ('device_pos', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.device')),
                ('temperature', models.FloatField(default=24.0)),
            ],
            bases=('homes.device',),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.device')),
                ('speed', models.IntegerField(default=1)),
                ('swing', models.BooleanField(default=False)),
            ],
            bases=('homes.device',),
        ),
        migrations.CreateModel(
            name='Lightbulb',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.device')),
                ('brightness', models.IntegerField(default=100)),
                ('colour', models.CharField(default='#FFFFFF', max_length=50)),
            ],
            bases=('homes.device',),
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.device')),
                ('volume', models.IntegerField(default=20)),
                ('channel', models.IntegerField(default=1)),
                ('is_mute', models.BooleanField(default=False)),
            ],
            bases=('homes.device',),
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='homes.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homes.home')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='homes.room'),
        ),
    ]
