# Generated by Django 5.2.7 on 2026-01-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_alter_positionhistory_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
