# Generated by Django 5.2.7 on 2026-01-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_device_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
    ]
