# Generated by Django 5.2.7 on 2026-01-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_device_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconditioner',
            name='fan_level',
            field=models.IntegerField(default=1),
        ),
    ]
