# Generated by Django 5.2.7 on 2026-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_airconditioner_fan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rotation_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='device',
            name='rotation_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='device',
            name='rotation_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='rotation_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='rotation_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='rotation_z',
            field=models.FloatField(default=0.0),
        ),
    ]
