# Generated by Django 5.2.7 on 2026-03-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_device_rotation_x_device_rotation_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='position_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='position_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='position_z',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='rotation_y',
            field=models.FloatField(default=0.0),
        ),
    ]
