# Generated by Django 5.2.7 on 2026-02-08 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0006_device_rotation_x_device_rotation_y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('time', models.TimeField(blank=True, null=True)),
                ('repeat_days', models.JSONField(default=list)),
                ('action', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('sunrise_sunset', models.BooleanField(default=False)),
                ('solar_event', models.CharField(blank=True, choices=[('sunrise', 'Sunrise'), ('sunset', 'Sunset')], max_length=20, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='homes.device')),
            ],
        ),
    ]
