# Generated by Django 5.2.7 on 2026-03-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_room_position_x_room_position_y_room_position_z_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='anchor_uuid',
            field=models.CharField(blank=True, help_text='WebXR persistent anchor UUID for restoring room position', max_length=255, null=True),
        ),
    ]
