# Generated by Django 5.2.7 on 2026-03-02 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_automation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartMeter',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homes.device')),
            ],
            bases=('homes.device',),
        ),
    ]
