# Generated by Django 5.2.7 on 2026-03-07 10:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_room_anchor_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('furniture_name', models.CharField(max_length=255)),
                ('furniture_type', models.CharField(default='Chair', max_length=50)),
                ('device_pos', django.contrib.gis.db.models.fields.PointField(blank=True, dim=3, null=True, srid=4326)),
                ('rotation_x', models.FloatField(default=0.0)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('rotation_z', models.FloatField(default=0.0)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture', to='homes.room')),
            ],
        ),
    ]
