# Generated by Django 5.2.7 on 2024-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0010_room_room_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_model_file',
            field=models.FileField(blank=True, help_text='Uploaded 3D model file (GLTF/GLB)', null=True, upload_to='room_models/'),
        ),
    ]
