# Generated by Django 5.2.7 on 2026-03-08 18:12

import homes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0011_room_room_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_model_file',
            field=models.FileField(blank=True, help_text='Uploaded 3D model file (GLTF/GLB)', null=True, upload_to=homes.models.room_model_upload_path),
        ),
    ]
