# Generated by Django 5.2.7 on 2026-03-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_automation'),
        ('homes', '0012_alter_room_room_model_file'),
    ]

    operations = [
    ]
