# Generated by Django 5.2.7 on 2026-03-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0008_smartmeter'),
        ('homes', '0013_merge_0007_automation_0012_alter_room_room_model_file'),
    ]

    operations = [
    ]
