# Generated by Django 5.2.7 on 2025-12-20 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userhome'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userhome',
            new_name='home_userho_user_id_39a909_idx',
            old_name='home_userho_user_id_home_i_idx',
        ),
        migrations.RenameIndex(
            model_name='userhome',
            new_name='home_userho_home_id_e0d7d9_idx',
            old_name='home_userho_home_id_idx',
        ),
        migrations.AlterField(
            model_name='positionhistory',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
        ),
    ]
