/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomesRouteImport } from './routes/homes'
import { Route as FurnitureRouteImport } from './routes/furniture'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityIndexRouteImport } from './routes/activity/index'
import { Route as HomesHomeIdRouteImport } from './routes/homes.$homeId'
import { Route as ActivityDeviceIdRouteImport } from './routes/activity/$deviceId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesRoute = HomesRouteImport.update({
  id: '/homes',
  path: '/homes',
  getParentRoute: () => rootRouteImport,
} as any)
const FurnitureRoute = FurnitureRouteImport.update({
  id: '/furniture',
  path: '/furniture',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIndexRoute = ActivityIndexRouteImport.update({
  id: '/activity/',
  path: '/activity/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomesHomeIdRoute = HomesHomeIdRouteImport.update({
  id: '/$homeId',
  path: '/$homeId',
  getParentRoute: () => HomesRoute,
} as any)
const ActivityDeviceIdRoute = ActivityDeviceIdRouteImport.update({
  id: '/activity/$deviceId',
  path: '/activity/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/devices': typeof DevicesRoute
  '/furniture': typeof FurnitureRoute
  '/homes': typeof HomesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/activity/$deviceId': typeof ActivityDeviceIdRoute
  '/homes/$homeId': typeof HomesHomeIdRoute
  '/activity/': typeof ActivityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/devices': typeof DevicesRoute
  '/furniture': typeof FurnitureRoute
  '/homes': typeof HomesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/activity/$deviceId': typeof ActivityDeviceIdRoute
  '/homes/$homeId': typeof HomesHomeIdRoute
  '/activity': typeof ActivityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation': typeof AutomationRoute
  '/devices': typeof DevicesRoute
  '/furniture': typeof FurnitureRoute
  '/homes': typeof HomesRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/activity/$deviceId': typeof ActivityDeviceIdRoute
  '/homes/$homeId': typeof HomesHomeIdRoute
  '/activity/': typeof ActivityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automation'
    | '/devices'
    | '/furniture'
    | '/homes'
    | '/login'
    | '/register'
    | '/settings'
    | '/activity/$deviceId'
    | '/homes/$homeId'
    | '/activity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automation'
    | '/devices'
    | '/furniture'
    | '/homes'
    | '/login'
    | '/register'
    | '/settings'
    | '/activity/$deviceId'
    | '/homes/$homeId'
    | '/activity'
  id:
    | '__root__'
    | '/'
    | '/automation'
    | '/devices'
    | '/furniture'
    | '/homes'
    | '/login'
    | '/register'
    | '/settings'
    | '/activity/$deviceId'
    | '/homes/$homeId'
    | '/activity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationRoute: typeof AutomationRoute
  DevicesRoute: typeof DevicesRoute
  FurnitureRoute: typeof FurnitureRoute
  HomesRoute: typeof HomesRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ActivityDeviceIdRoute: typeof ActivityDeviceIdRoute
  ActivityIndexRoute: typeof ActivityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes': {
      id: '/homes'
      path: '/homes'
      fullPath: '/homes'
      preLoaderRoute: typeof HomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/furniture': {
      id: '/furniture'
      path: '/furniture'
      fullPath: '/furniture'
      preLoaderRoute: typeof FurnitureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/': {
      id: '/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof ActivityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homes/$homeId': {
      id: '/homes/$homeId'
      path: '/$homeId'
      fullPath: '/homes/$homeId'
      preLoaderRoute: typeof HomesHomeIdRouteImport
      parentRoute: typeof HomesRoute
    }
    '/activity/$deviceId': {
      id: '/activity/$deviceId'
      path: '/activity/$deviceId'
      fullPath: '/activity/$deviceId'
      preLoaderRoute: typeof ActivityDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HomesRouteChildren {
  HomesHomeIdRoute: typeof HomesHomeIdRoute
}

const HomesRouteChildren: HomesRouteChildren = {
  HomesHomeIdRoute: HomesHomeIdRoute,
}

const HomesRouteWithChildren = HomesRoute._addFileChildren(HomesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationRoute: AutomationRoute,
  DevicesRoute: DevicesRoute,
  FurnitureRoute: FurnitureRoute,
  HomesRoute: HomesRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ActivityDeviceIdRoute: ActivityDeviceIdRoute,
  ActivityIndexRoute: ActivityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
